# Generated by Django 3.2.12 on 2024-12-12 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome_aluno', models.CharField(max_length=255)),
                ('matricula_aluno', models.CharField(max_length=255)),
                ('foto_aluno', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nome_evento', models.CharField(max_length=255)),
                ('foto_evento', models.ImageField(blank=True, null=True, upload_to='')),
                ('id_aluno', models.ForeignKey(db_column='id_aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='refeitorioApp.aluno')),
            ],
        ),
    ]
